generate_image:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: venice_ai
    prompt:
      required: true
      selector:
        text:
          multiline: true
    model:
      selector:
        text:
    size:
      default: "1024x1024"
      selector:
        select:
          options:
            - "auto"
            - "256x256"
            - "512x512"
            - "1024x1024"
            - "1536x1024"
            - "1024x1536"
            - "1792x1024"
            - "1024x1792"
    quality:
      default: standard
      selector:
        select:
          options:
            - auto
            - low
            - medium
            - high
            - standard
            - hd
    style:
      default: vivid
      selector:
        select:
          options:
            - vivid
            - natural
